# Generated by Django 2.2.24 on 2021-06-15 20:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EolVimeoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edx_video_id', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid edx_video_id', message='edx_video_id has invalid characters', regex='^[a-zA-Z0-9\\-_]*$')])),
                ('vimeo_video_id', models.CharField(blank=True, max_length=50)),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(default=None, max_length=255)),
                ('url_vimeo', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('error_description', models.TextField(blank=True, null=True, verbose_name='Error Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('edx_video_id', 'user')},
                'index_together': {('edx_video_id', 'user')},
            },
        ),
    ]
